#!/usr/bin/env python

import os
import sys
from datetime import datetime
from . import git_handler
from . import github_client
from .github_tools import create_pull_request as api_create_pr, create_branch, commit_file
from .code_tools import run_linter, check_complexity

def generate_feature_branch_name():
    """Generate a unique feature branch name based on timestamp."""
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    return f"auto-evolve/feature-{timestamp}"

def validate_code(code_content):
    """
    Validate code using linting and complexity checks.
    
    Returns:
        dict: Validation results with 'passed', 'errors', 'warnings', 'metrics'
    """
    linting_result = run_linter(code_content)
    complexity_result = check_complexity(code_content)
    
    return {
        'passed': linting_result.get('passed', False) and complexity_result.get('passed', True),
        'linting': linting_result,
        'complexity': complexity_result
    }

def create_commit_content(title, changes_description):
    """
    Create commit message and code changes.
    
    Args:
        title: Name of the feature/change
        changes_description: Description of what changed
    
    Returns:
        dict: Contains 'commit_message' and 'file_changes'
    """
    commit_message = f"Auto-Evolve: {title}\n\n"
    commit_message += f"Description: {changes_description}\n"
    commit_message += f"Generated by auto-evolve system on {datetime.now().isoformat()}"
    
    return {
        'commit_message': commit_message,
        'changes': f"# {title}\n\n{changes_description}"
    }

def main():
    """
    Main workflow to automate PR creation.
    
    Environment variables expected:
    - GITHUB_TOKEN: GitHub authentication token
    - TARGET_REPOSITORY: Repository in 'owner/repo' format
    - TARGET_BRANCH: Target branch for the PR (default: 'dev')
    - FEATURE_TITLE: Title of the feature
    - FEATURE_DESCRIPTION: Description of changes
    """
    print("[AutoPR] Starting automated PR creation workflow...")
    
    # Get environment variables
    target_repo = os.getenv('TARGET_REPOSITORY', os.getenv('GITHUB_REPOSITORY', ''))
    target_branch = os.getenv('TARGET_BRANCH', 'dev')
    feature_title = os.getenv('FEATURE_TITLE', 'Auto-Generated Feature')
    feature_description = os.getenv('FEATURE_DESCRIPTION', 'This is an automatically generated feature.')
    
    if not target_repo:
        print("[AutoPR] ERROR: TARGET_REPOSITORY not set")
        return False
    
    try:
        # Step 1: Generate feature branch name
        feature_branch = generate_feature_branch_name()
        print(f"[AutoPR] Created feature branch name: {feature_branch}")
        
        # Step 2: Create feature branch
        print(f"[AutoPR] Creating branch {feature_branch} from {target_branch}...")
        try:
            branch_result = create_branch(target_repo, feature_branch, target_branch)
            print(f"[AutoPR] Branch created successfully")
        except Exception as e:
            print(f"[AutoPR] Warning: Branch creation may have issues: {e}")
            # Continue anyway as branch might already exist
        
        # Step 3: Create content for the PR
        content_data = create_commit_content(feature_title, feature_description)
        commit_message = content_data['commit_message']
        code_changes = content_data['changes']
        
        # Step 4: Validate the code (demo - in real scenario would be actual generated code)
        print(f"[AutoPR] Validating code...")
        validation = validate_code(code_changes)
        print(f"[AutoPR] Validation passed: {validation['passed']}")
        
        if validation['linting'].get('errors'):
            print(f"[AutoPR] Linting errors found:")
            for error in validation['linting']['errors']:
                print(f"  - {error}")
        
        # Step 5: Commit file to feature branch
        file_path = f"generated/{feature_branch.split('/')[-1]}.md"
        print(f"[AutoPR] Committing changes to {file_path}...")
        try:
            commit_result = commit_file(
                target_repo,
                feature_branch,
                file_path,
                code_changes,
                commit_message
            )
            print(f"[AutoPR] Commit successful")
        except Exception as e:
            print(f"[AutoPR] Commit failed: {e}")
            return False
        
        # Step 6: Create pull request
        pr_title = f"{feature_title} ({datetime.now().strftime('%Y-%m-%d')})"
        pr_body = f"""## Automated PR from Auto-Evolve System

### Changes
{feature_description}

### Validation Results
- Linting: {'PASSED' if validation['linting'].get('passed') else 'FAILED'}
- Complexity Score: {validation['complexity'].get('cyclomatic_complexity', 'N/A')}
- Max Nesting Level: {validation['complexity'].get('max_nesting_level', 'N/A')}

### Generated Files
- {file_path}

---
*Generated by auto-evolve automation system*
"""
        
        print(f"[AutoPR] Creating pull request...")
        pr_result = api_create_pr(
            repo=target_repo,
            title=pr_title,
            head=feature_branch,
            base=target_branch,
            body=pr_body
        )
        
        pr_number = pr_result.get('number')
        pr_url = pr_result.get('html_url')
        
        print(f"[AutoPR] ✅ SUCCESS: PR created!")
        print(f"[AutoPR] PR #{pr_number}: {pr_url}")
        
        return {
            'success': True,
            'pr_number': pr_number,
            'pr_url': pr_url,
            'branch': feature_branch,
            'validation': validation
        }
        
    except Exception as e:
        print(f"[AutoPR] ❌ ERROR: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == '__main__':
    result = main()
    sys.exit(0 if result and isinstance(result, dict) and result.get('success') else 1)
