/**
 * This is an example module generated by the auto-evolve agent.
 * Its purpose is to demonstrate the code generation capabilities of the worker.
 */

/**
 * A simple function that returns a greeting.
 * @param {string} [name='World'] - The name to greet.
 * @returns {string} A greeting message.
 */
function greet(name = 'World') {
  return `Hello, ${name}!`;
}

/**
 * An example class.
 */
class Example {
  constructor() {
    this.createdAt = new Date();
  }

  /**
   * Logs the creation timestamp of the instance.
   */
  logCreationTime() {
    console.log(`Example instance created at: ${this.createdAt.toISOString()}`);
  }
}

module.exports = {
  greet,
  Example,
};
